### ISSUE TITLE
Unable run

### ISSUE THREAD

**Issue by arkadiyala** [swtestacademy/ExtentReportsExample#1]
I have cloned this project . Right click on TestNG.xml and  run as TestNG suite.
I got below error message. Could you please help me.
![image](https://user-images.githubusercontent.com/21693119/38996753-7b6087f4-43b1-11e8-80fa-213a7326ea9c.png)

**Comment by arkadiyala** [comment]
Please see below screen shots for more information . Please help me.

![image](https://user-images.githubusercontent.com/21693119/39018933-42083a60-43ed-11e8-81e7-97015e2ad856.png)

![image](https://user-images.githubusercontent.com/21693119/39018921-32c91ef2-43ed-11e8-9a7c-5a1a08cb364e.png)

**Comment by swtestacademy** [comment]
Maximize window is base class commented out. Please try again. Now it is working.
