### ISSUE TITLE
java.lang.NullPointerException on try to launch individual tests 

### ISSUE THREAD

**Issue by BorjaRobles** [swtestacademy/ExtentReportsExample#2]
On intellij on try to launch tests one by one gives a NullPointerException

![screenshot 2019-01-18 at 22 05 01](https://user-images.githubusercontent.com/1125951/51412862-4b497000-1b6d-11e9-8f0b-095a8ea153b3.png)

For this to run I have to launch the .xml file

**Comment by swtestacademy** [comment]
It has been fixed.
